/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentids;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertTrue(App.test1());
    }

    @Test void test2() {
        assertTrue(App.test2());
    }
}
