/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gameusernames;

import java.util.HashMap;
import java.util.Optional;

public class App {

    private static class Attribute<T> {
        public final String name;
        public final String description;

        public final T value;       

        public Attribute(String name, String description, T value) {
            this.name = name;
            this.description = description;
            this.value = value;
        }

        @Override 
        public String toString() {
            return String.format("(%s: %s)", name, value);
        }
    }

    private static class Player {
        public final String username;
        private final HashMap<String, Attribute<Object>> attributes = new HashMap<>();

        public Player(String username) {
            this.username = username;
        }

        public void addAttribute(Attribute<Object> attribute) {
            attributes.put(attribute.name, attribute);
        }

        public Optional<Attribute<Object>> getAttribute(String name) {
            return Optional.ofNullable(attributes.get(name));

        }

        @Override 
        public String toString () {
            String output = username + "\n";

            for (Attribute<Object> attribute : attributes.values()) {
                output += "  - " + attribute.toString() + "\n";
            }

            return output;
        }
    }

    private static class Game {
        private final HashMap<String, Player> players = new HashMap<>();

        public void addPlayer(Player player) {
            players.put(player.username, player);
        }

        public Optional<Player> getPlayer(String username) {
            return Optional.ofNullable(players.get(username));
        }

        @Override 
        public String toString() {
            String output = "";

            for (Player player : players.values()) {
                output += player.toString() + "\n";
            }

            return output;
        }
    }

    public static void main(String[] args) {
        Game game = new Game();

        Player player1 = new Player("player1"); 
        player1.addAttribute(new Attribute<>("health", "The player's health", 100)); 
        player1.addAttribute(new Attribute<>("score", "The player's score", 15)); 
        game.addPlayer(player1); 

        Player player2 = new Player("player2"); 
        player2.addAttribute(new Attribute<>("health", "The player's health", 75)); 
        player2.addAttribute(new Attribute<>("score", "The player's score", 0)); 
        game.addPlayer(player2);

        System.out.println(game);
    }
}
