/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gameusernames;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void satisfiesTest1() {
        assertTrue(App.test1());
    }

    @Test void satisfiesTest2() {
        assertTrue(App.test2());
    }
}
